---
title: "Introduction to R Markdown"
subtitle: "WILD2900"
date: "updated on `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This material borrows heavily from the [Learning R](learnr.usu.edu) course developed by Tom Edwards at Utah State University. 

# What is Markdown?

Before we discuss what R Markdown is, we need to discuss what Markdown is. What is Markdown? Let's start with what it's not.  

Many of you have probably created a report or a paper using a word processor like Microsoft Word or Google Docs. Word processors are referred to as "what you see is what you get" (*wysiwyg*) text editors. This means that when you hightlight text and click the `boldface` icon in Word, the text appears bold on your screen. All sorts of other formatting options, incluing making headers, inserting figures, adding page numbers, etc., are possible by clicking on buttons. There is code behind the scenes that creates these changes but users don't see the code, only the formatting output. This makes *wysiwyg* editors relatively easy to use for beginners. But for more advanced users, it can actually be problematic. Have you ever had Word act in ways that you don't fully understand? Of course! We all have. Have you ever tried opening a `.docx` file using an older version of Word, only to find that it doesn't look the way thought it would? Have you ever inserted a figure only to have it jump to another page or get 'anchored' to the bottom of a page? These are just a few of the problems that occur when your document has a bunch of hidden formatting code that you cannot see or understand.  

Markdown is different. Markdown files are plain text files, meaning that they be created and edited using text editors (like NotePad on Windows or TextEdit on Mac). The biggest difference between Markdown files and Word documents is that formatting Markdown documents occurs in the document itself rather than behind the scenes. So to make something **boldface** you have to tell Markdown to do that by putting two `**asterisks**` on either side of the word or phrase. *Italics* is done by putting one `*asterisk*` around the text. [Hyperlinks](https://en.wikipedia.org/wiki/Markdown) are written like this: `[Hyperlinks](https://en.wikipedia.org/wiki/Markdown)`. These are just a few of the many formatting options you can include in a Markdown document. We'll learn about options like headers, lists, mathematical symbols and equations, and figures later in this tutorial and throughout the semester.

As you're writing, the text won't look bold or italic or whatever (this is not 'what you see is what you get', it's 'what you see is what you type'). The formatting only shows up when you render the Markdown file to create another type of document (pdf, html, even Word). The nice thing about Markdown is that because it uses standard ways to express specific formatting options, you can convert your documents into different output formats very easily. 

# What is R Markdown?

In this course, we will use a specific 'flavor' of Markdown called 'R Markdown'. R Markdown gives us all of the formatting options available for Markdown *plus* the ability to embed, display, and run R code in our documents. By mixing R code with plain text, we can create dynamic reports that replicate the analytical processes, show the code underlying these processes, create the output from our analysis (figures, summary statistics, etc.), and provide all of the necessary text explanations to go along with the code and output. As Tom Edwards puts it, R Markdown documents "can be, for all intent and purpose, your research metadata."

# Why use R Markdown

R Markdown has many advantages compared to creating reports in Word or GoogleDocs. These advantages include:

1) **Versatility**- Want to convert a Word document into pdf? That's not too hard. But pdf to Word? That's a pain. PDF to HTML? Maybe you know how to do that but I don't. With R Markdown, we can change between these formats with a single click (or a single line of code). You can even convert them into pretty nice slideshows.  

2) **Embed code in text** - After running an analysis, how do you get your results into Word? Type them by hand? Copy-and-paste? Both are a pain and error prone. Rerun your analysis using new data? Oops, now you have to copy and paste those new results and figures. With R Markdown, we embed code directly into the text so results and figures get added to our reports automatically. That means no copying and pasting and updating reports as new results come in is pain free.  

3) **Annotate your code** - Using the `#` is great for adding small annotations to your R scripts and you should defitinely get in the habitat of doing that. But sometimes you need to add a lot of details to help other users (or your future self) make sense of complex code. R Markdown allows you to create documents with as much text and formatting as you need, along with the code.  

4) **Version control** - Tired of saving `manuscript_v1.doc`, `manuscript_v2.doc`, `manuscript_final.doc`, `manuscript_final_v2.doc`? Then version control is for you. We won't go into the specfics here but R Markdown allows you to seamlessly use version control systems like git and Github to document changes to your reports.  

5) **Edit as text files** - R Markdown files are most easily created and editted within RStudio but you don't have to do it that way. They can be opened and edited in base R and even using text editors. This means you can create and edit them on any platform (Windows, Mac, Linux) using free software that is already installed on the computer

6) **Stability** - How many of us have had Word crash while we're working on a paper? Did you save as you were working? Hope so. Because R Markdown files are smaller and more lightweight, they tend not to cause your computer to crash as you're working on them. 

7) **Focus on text, not formatting** - Do you spend a lot of time tweaking the formatting of your Word document rather than writing? R Markdown allows you to separate the writing process from the formatting process, which allows you to focus on the former without worrying about that later (in theory at least). Plus there are lots of templates you can use to ensure that the formatting is taken care without you having to do anything special! 

# Why not use R Markdown?

There are a few disadvantages to R Markdown.

1) **Your advisor doesn't use it** - Try sending a `.Rmd` file to your advisor to get feedback. I'll wait... Like it or not, most folks still use word processors, so if you adopt R Markdown you will still have to create and edit Word documents for some collaborators who are stuck in their ways

2) **No track changes** - Even if you're lucky to have an advisor who will review a `.Rmd` file, you won't get nice track changes like in Word. There are alternative to this (version control helps) but not are quite as easy as track changes. 

3) **Fewer formatting options** - For better or worse, you have a more limited set of formatting options with R Markdown. That can be constraining (but often it's actually freeing!)

4) **There's a learning curve** - You already know how to use Word. R Markdown is new. How do you make something bold? How do you insert equations? How do you get figures to go at the end of your document? At first, you will almost certaintly have to google almost every thing you need to do in R Markdown (this is why number 1 is a problem). Most of it is pretty simple but it still means the going can be slow at first. 

# Authoring R Markdown files

Understanding what R Markdown files are and why they are so useful will become more clear as you learn to create and edit these documents. So without futher ado, let's create an new R Markdown file and do some basic editing. 

## Step 0: Set up the file structure

We've already learned about RStudio projects and directory structure so let's put that knowledge into practice. The document we are going to create will form the basis of your first homework assignment so to start off the semster in an organized fashion, let's create a project called `WILD6900`:

0a) Click on `File -> New Project` then click `New Directory`

0b) Click `New Project`. Name this project `WILD6900` and choose a sensible location for the project (e.g., `Desktop/`)

0c) Click `Create Project` at the bottom. 

1d) In the newly create directory, create a subdirectory called `LastNameFirstName-Homework#`, replacing `LastNameFirstName` with your last and first names and `#` with the appropriate homework number

## Step 1: Create a new R Markdown file using the homework template

1a) Click on `File -> New File -> R Markdown...`

1b) In the window on the left, select `From Template`

1c) Scroll down through the options until you see `WILD6900-Homework1`. Select that template 

1d) In the `Name:` window type `LastnameFirstname-homework1`, substituting your last and first names. In the `Location` window, navigate to your newly create `LastNameFirstName-Homework#` directory

1e) Click `Ok`

## Step 2: Fill in your information and render the document

2a) Change the `author: YOUR NAME HERE` field in the header to your name. 

2b) You should see a small box above the `Source` window (the RStudio window where your document just appeared) that says `Knit` with a small ball of yarn icon. When you click that button (not yet!), two things will happen:

*The .Rmd file will be rendered as a PDF document, which will pop up on your screen

* RStudio will create a new file called `Assignment1.pdf` - you should see that file in the `Files` window in the bottom right of your screen

2c) Click that button

Congratulations, you just created your first R Markdown file!

# Basic formatting

## The YAML header

At the top of your `.Rmd` file, you should see several line in between three blue dashes:
```
---
title: "WILD6900"
subtitle: "Homework 1"
author: "YOUR NAME HERE"
output: pdf_document
---
```

This is called the "YAML header" and it's where we can control a lot of the major formatting options for our documents. For example, to change the output to HTML, just switch `pdf_document` for `HTML_document` and then click the `Knit` button again (be sure to change it back to pdf after you try it for yourself)

Pretty cool, right?

The YAML header allows to control many "high level" options for our document. For example, to change the font size, type the following directly under the `output: pdf_document` argument:

```
fontsize: 12pt
```
Check to see that the font size changed by clicking `Knit`. 

Changing font type is a little trickier. Behind the scenes, R Markdown turns your document into Latex code (another), which is then converted into a pdf. You don't need to know much about Latex (though a little knowledge is helpful) but this conversion does mean that our formatting options have to passed to the Latex convertor in specific ways. To tell Latex that we want to use `Arial` font, we have to modify the `output:` argument as follows:

```
title: "WILD6900"
subtitle: "Homework 1"
author: "YOUR NAME HERE"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    latex_engine: xelatex

mainfont: Arial
```

Make sure you include the spaces to indent `pdf_document:` and `latex_engine: xelatex`. 

To indent the first line of each paragraph, add the following to the header:

```
indent: true
```

There many possible options for the header (see [here](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf) for additional examples). We'll learn more about some of these options later in the semester. 

## Headers

Using headers is a natural way to break up a document or report into smaller sections. You can include headers by putting one or more `#` signs in front of text. One `#` is a main header, `##` is the secondary header, etc.

# Header 1

## Header 2

###  Header 3

## Paragraph and line breaks

When writing chunks of text in R Markdown (e.g., a report or manuscript), you can create new paragraphs by leaving an empty line between each paragraph:

```
This is one paragraph.

This is the next paragraph
```

If you want to force a line break, include two spaces at the end of the line where you want the break:

```
This is one line  
This is the next line
```

## **Bold**, *Italics*, 

As mentioned earlier, create **boldface** by surrounding text with two asterisks (`**bold**`) and use single asterisks for *italics* (`*italics*`)

## Code type

To highlight code (note, this does not actually insert functioning code, just formats text to show that it is code rather than plain text), surround the text with back ticks ": `mean()`

You can include muliple lines of code by including three back ticks on the line before the code and then three back ticks on the line after the code:

```
Multiple lines of code
look like 
this
```

## Bulleted lists

* Bulleted lists can be included by starting a line with an asterisk

* You can also start the lines with a single dash `-`

  + for sub-bullets, indent the line and start it with `+`
    - for sub-sub-bullets, indent twice (press `tab` two times) and start with `-`

## Numbered lists

1. Numbered lists look like this

2. You can also include sub-levels in number lists
    i) these can be lower case roman numerals  
    a. or lowercase letters  
      B. or uppercase letters  
    
## Quotations

You highlight quotations by starting the line with `>`, which produces:

>All models are wrong

## Hyperlinks

Insert hyperlinks by putting the text you want displayed in square brackets followed by the link in parentheses: `[RStudio cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)`

## Equations

Inserting equations in R Markdown is where knowing some Latex really comes in handy becuase eqations are written using Latex code. For the most part, this is not too difficult but if you need to insert complex equations you will probably need to look up the code for some symbols. There are many good resources for if you google "latex equations" or something similear.

### Inline vs. block equations

You can include equations either inline ($e = mc^2$) or as a stand-alone block:

$$e=mc^2$$

Inline equations are added by putting a single dollar sign `$` on either side of the equation (`$e=mc^2$`). Equation blocks are create by starting and ending a new line with double dollar signs

`$$e=mc^2$$`

## Greek letters

Statistical models include a lot of Greek letters ($\alpha, \beta, \gamma$, etc.). You can add Greek letters to an equation by typing a backslash `\` followed by the name of the letter `\alpha`. Uppercase and lower case letters are possible by capitalizing the name ($\Delta$ = `$\Delta$`) or not ($\delta$ = `$\delta$`).

## Subscripts and superscripts

You can add superscripts using the `^` ($\pi r^2$=`$\pi r^2$`) symbol and subscripts using an underscore `_` ($N_t$ = `$N_t$`). 

If the superscript or subscript includes more than one characeter, put the entire script within curly brackets `{}`: $N_t-1 \neq N_{t-1}$ is `$N_t-1 \neq N_{t-1}$`

## Brackets and parentheses

You can add normal sized brackets and parenthesis just by typing them into the equation: $(x + y)$ = `(x + y)`

If you need bigger sizes, using `$\big($`, `$\bigg($`, and `$\Bigg($` produces $\big($, $\bigg($, and $\Bigg($ (switch the opening parenthesis for a closing parenthesis or square bracket as needed)

## Fractions

Fractions can either be inline ($1/n$ = `$1/n$`) or stacked ($\frac{1}{n}$ = `$\frac{1}{n}$`). For stacked equations, the terms in the first curly brackets are the numerator and the terms in the second curly brackets are the demoninator. 


## Operators

Pretty much every operator you could need can be written in latex. Some common ones include $\times$ (`$\times$`), $\lt$ (`$\lt$`), $\gt$ (`$\gt$`), $\leq$ (`$\leq$`), $\geq$ (`$\geq$`), $\neq$ (`$\neq$`), $\sum$ (`$\sum$`), $\prod$ (`$\prod$`), $\infty$ (`$\infty$`), and $\propto$ (`$\propto$`).

See [here](http://web.ift.uib.no/Teori/KURS/WRK/TeX/symALL.html) for a list of other operators. 

# Adding code


# Homework assignment 1

# Additional resources

From the RStudio tool bar, click `Help -> Cheatsheets` and then select the `R Markdown cheat sheet` (lots of other good cheat sheets there as well)

RStudio's [R Markdown](https://rmarkdown.rstudio.com/lesson-1.html) tutorial  

Tom Edward's [R Markdown](http://learnr.usu.edu/r_markdown/1_1_markdown.php) tutorial  
